import axios from "axios";

const BACKEND_URL = 'https://react-native-course-e365a-default-rtdb.firebaseio.com'
export const storeExpense = async (expenseData) => {
    const response = await axios.post(BACKEND_URL + '/expense.json', expenseData);
    const id = response.data.name; // get id generated by firebase when add new object(it returned it on name property)

    return id;
}

export const fetchExpenses = async () => {
    const response = await axios.get(BACKEND_URL + '/expense.json');
    const expenses = [];

    console.log('response = ', response.status);
    for (const key in response.data) {
        const responseObj = {
            id: key,
            amount: response.data[key].amount,
            date: new Date(response.data[key].date),
            description: response.data[key].description
        };

        expenses.push(responseObj);
    }
    return expenses;
}

export const updateExpense = (id, expenseData) => {
    return axios.put(BACKEND_URL + `/expense/${id}.json`, expenseData);
}

export const deleteExpense = (id) => {
    return axios.delete(BACKEND_URL + `/expense/${id}.json`);
}
